name: LB2 - GitHub Actions
run-name: ${{ github.actor }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on:
      group: Noah
      labels: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_NOAH }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NOAH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: astut0/ab04:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply --validate=false -f namespace.yml
          kubectl apply --validate=false -f deployment.yml
          kubectl apply --validate=false -f service.yml
          kubectl apply --validate=false -f ingress.yml

        - name: Verify deployment rollout
          run: |
            kubectl rollout status deployment/ab05 -n m324-csbe-lezama
            kubectl get pods -n m324-csbe-lezama
