name: LB2 - GitHub Actions
run-name: ${{ github.actor }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on:
      group: Noah
      labels: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_NOAH }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NOAH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: astut0/ab04:latest

      - name: Configure access to Kubernetes
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml set image deployment/ab04 ab04=astut0/ab04:latest -n m324-csbe-lezama
          kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/ab04 -n m324-csbe-lezama

      - name: Verify pods in Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml get pods -n m324-csbe-lezama
