name: LB2 - GitHub Actions
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker:
    runs-on:
      group: Noah
      labels: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_NOAH }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NOAH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: astut0/ab04:latest
