name: LB2 - GitHub Actions
run-name: ${{ github.actor }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    runs-on:
      group: Noah
      labels: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_NOAH }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NOAH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: astut0/ab04:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes Context
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f namespace.yml
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl apply -f ingress.yml

      - name: Verify deployment rollout
        run: |
          kubectl rollout status deployment/ab04 -n m324-csbe-lezama
          kubectl get pods -n m324-csbe-lezama
